### ISSUE TITLE
Sync single enquiry failing

### ISSUE THREAD

**Issue by tomclement** [rapidftr/tracker#195]
Syncing a single enquiry is now failing.

**Steps to Reproduce**
- Create and save an enquiry on the mobile
- While viewing that enquiry, select `Synchronise This Record` from the menu

**Expected Result**
That enquiry should be synced successfully

**Actual Result**
The sync operation fails. The server logs indicate the following error:
`RuntimeError (Expecting an array or keyed hash for property Enquiry#ids_marked_as_not_matching)`

**Comment by tomclement** [comment]
**[Update]** Sync single enquiry is now failing for only updates (and not create). 

**Steps to Reproduce**
- Create and save an enquiry on the mobile
- While viewing that enquiry, select `Synchronise This Record` from the menu (_This will work_)
- Now select the option to edit that enquiry and then make a change to the enquiry
- Save the enquiry and then select `Synchronise This Record` from the menu

**Expected Result**
That enquiry should be synced successfully

**Actual Result**
The sync operation fails. The server logs indicate the following errors:
`java.io.SyncFailedException` `Action Controller: Exception caught`

**Comment by ctumwebaze** [comment]
The server api expected the criteria used for finding potential matches to be present. If the criteria is empty, the server would reject the record with an error "Unprocessable entity". When the server criteria functionality was changed from storing the criteria on the actual entity to composing it on the fly and finding potential matches, the api check was not removed.

Also due to the refactoring on sync functionality on the mobile application, by introducing a uniform HttpDao object for all the entities, during the update process, the id of the entity wouldn't be sent along and the server wouldn't know which entity to update.
