### ISSUE TITLE
Fix expiration timeouts between mobile/browser and server

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#31]
The application stores encrypted cookies for 20min. This fix should ensure that sync doesn't fail when server and device have different timestamps.

If your device/client time is off by more than 20mins, the server automatically logs user out. The problem is that by the time client/device acquires the cookie, it's already expired.

**Comment by rdsubhas** [comment]
### Implementation Notes

Instead of relying on cookie expiration (which is relative to client time), Handle the session timeouts in the server side (relative to server time). So the expiration is counted as 20 minutes _from the server time_ you last accessed RapidFTR. References rapidftr/tracker#31

This is done by storing `last_access_time` on the cookie. This is safe, because we are using [encrypted cookies](https://github.com/hmcfletch/encrypted-cookie-store) and nobody will be able to tamper the cookies. The password for the encrypted cookie is randomly generated on the server and saved in CouchDB, so people cannot guess the password by looking at the source code as well.

Steps to verify:
- Wait until this pull request is merged and deployed to https://dev.rapidftr.com
- We used Chrome with the "EditThisCookie" extension which allows to see cookies
- Login to dev.rapidftr.com
- Check the cookies. You'll find a cookie called `_session`
- This is encrypted. It tracks your session ID and the last time you accessed the server. You won't be able to see or edit anything in this cookie
- Change your system time and refresh. But you won't be logged out. The server tracks 20 minutes relative to the server time. You don't need to keep the time on your browser/mobile in sync with the server anymore
- Wait for 20 minutes (don't do anything, or your session will be extended by 20 mins again). Refresh and the session will be logged out

**Comment by tomclement** [comment]
#### QA Remarks
- Functionality is ok. However, there is a need to make sure that users receive the correct error messages (such as on attempting to sync when their session has expired). This is to be covered with issue 30 - Better Error Messages (https://github.com/rapidftr/tracker/issues/30)
