### ISSUE TITLE
Remove all hard coded values in form sections

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#44]

**Comment by ctumwebaze** [comment]
The areas that need to be looked at here are:
- Child List page - Remove "name" being hardcoded, and use the highlight fields. MAY need to play the API first before doing this?
- Child Search - currently hardcoded to search Name & Unique ID, needs to search all the highlight fields instead
- "name" is hard-coded as a Database column, need to remove that
- Check the ChangeLogs (if any) in the mobile to see if any fields are hardcoded
- Enquiries??

**Comment by ctumwebaze** [comment]
Developer notes:
- Remove All Migrations - Start from a clean slate?
- Change DAO, Models and Tests
- Fix the Child List view
- Fix the Search

**Comment by ctumwebaze** [comment]
Developer notes:
- Remove All Migrations - Start from a clean slate?
- Change DAO, Models and Tests
- Fix the Child List view
- Fix the Search

**Comment by rdsubhas** [comment]
### Implementation Notes:
- Previously we used to have separate `name` and `id` columns in Android, and we did a `LIKE` on them for the quick search
- Now, we have to use the Highlighted Fields in order to do the search
- Problem is, the Child Data is stored as a single JSON column. We need to search specific fields inside this JSON blob directly from the database. The options explored were:
  - Sqlite `GLOB` is case sensitive, so not used
  - Sqlite `REGEXP` operator needs recompiling of SQLCipher, or the SQLCipher commercial edition. So this approach was also not used. Also doing regular expressions for matching JSON is not recommended
  - Loop through all records and search purely with Java code. But doing this completely in Java unacceptable for performance

### Approach we settled upon:
- Do a `LIKE` to get an initial set of matching records. Then upon these records, do Java based matching on the highlight fields

### Further optimizations to be done as part of #28
- Move searching to a background thread with a progress dialog
- Use Pagination with a Producer/Consumer pattern. i.e.
  - Have a `Producer` that takes as input the `Cursor` (with records filtered using `LIKE`), and this should loop through the cursor and yield only the matching children
  - A Consumer should pick 10 records from the producer and display it on the screen. When the user scrolls to the end of the page, then it should fetch the next 10 records, and so on.
  - Have a look at [RxJava](https://github.com/Netflix/RxJava/wiki) for some examples.

**Comment by tomclement** [comment]
Looks good,  save for #131

**Comment by tomclement** [comment]
Resolved with rapidftr/RapidFTR---Android#148 - Ready for acceptance
