### ISSUE TITLE
Bundle APK with Server

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#52]

**Comment by austiine04** [comment]
- Download the .apk from dropbox as part of the docker set up process from dropbox and add into the public folder as RapidFTR.apk
- This makes the .apk available at /RapidFTR.apk

**Comment by tomclement** [comment]
The APK is currently not available at the specified location (https://dev.rapidftr.com/RapidFTR.apk) Has this been deployed to dev.rapidftr.com yet? Additionally, could we change the location of the APK to /apk/RapidFTR.apk?

**Comment by ctumwebaze** [comment]
The issue here was that the url specified in the docker file pointed to a web page rather than an actual file. The right url is https://www.dropbox.com/sh/y9cjomps39deqb6/AAB2ieXvhcohg_4J0BC3j2GXa/Android/RapidFTR-dev.apk?dl=1

**Comment by tomclement** [comment]
The apk can only be downloaded using a desktop browser, as opposed to a browser on a mobile device. Attempting to download the apk using a mobile device results in an infinite download

**Comment by tomclement** [comment]
Problem with downloading the APK using a mobile device is now resolved with rapidftr/RapidFTR/pull/692. 

The fix was to ensure that if a request for an APK comes in over HTTPS, it is redirected to HTTP. This effectively solves the problem of the android device going into an infinite loop because it does not trust a self-signed certificate on the deployed RapidFTR instance
