### ISSUE TITLE
Show list of matching child records when viewing an enquiry

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#58]
When viewing a child record on their mobile device, a field worker will be able to view the list of enquiries that matched the record. The field worker will navigate to a section of the child record details which will display the list of enquiries that match this child record.

![screen shot 2014-08-21 at 2 58 15 pm](https://cloud.githubusercontent.com/assets/4676831/3995690/0e9a7b38-292b-11e4-9b85-da4aa2e31557.png)

**Comment by scampo** [comment]
@baziwane can the team provide some context on the logical model for identifying potential matches?

**Comment by andreweskeclarke** [comment]
1. Since there is no information about what is in each field, we can not pick which fields to match against in the code (can't hard code).
2. In the Android DB and the Web DB, the children and the enquiries will be saved in a format and hierarchy very similar to what you'd see in the UI.
3. When we want to search a matching child, we will take all the fields on an enquiry and squash them into a long string and search through the children, almost like you had typed all that information into the search bar.  It works this way already if you look at MatchService.search_for_matching_children

We need more clarification on if there should a cut off for potential matches (like top 10? any fields have higher priority over others?)

**Comment by baziwane** [comment]
@scampo I hope that makes sense?

**Comment by scampo** [comment]
1. Does this just mean that we need to be able to click "mark as
   searchable _for
   Smart Search_" when building form fields? Or is this opening a can of worms
   and compromising the feature?
2. OK
3. Can we talk more about how this will work?
4. for cut-off, let's discuss some options for how to approach this --
   weighting fields, ranking, etc.

_____________________
Stuart Campo
Innovation Unit, UNICEF
scampo@unicef.org

+254.718.764526 (Kenya)*
+211.921.379121 (South Sudan)
+256.779.234347 (Uganda)
+1.802.249.8233 (U.S.)
 Skype: stuart.campo

*_currently in Kenya_

www.unicefstories.org

**Comment by baziwane** [comment]
GIVEN that I am a FIELD WORKER
WHEN I am viewing details of an enquiry on my mobile device
THEN I should be able to view an icon/link to matching child records

GIVEN that I am a FIELD WORKER
WHEN I navigate to the page upon clicking on icon of matching child records
THEN I should see the list of child records that match the enquiry

**Comment by scampo** [comment]
This is accurate. We will just want to be very clear on the language
between "Potential Match" and "Confirmed Match", and think about how this
will visualize.

So:
GIVEN that I am a CHILD PROTECTION SPECIALIST
WHEN I confirm a match on the web interface of RapidFTR for a case managed
by one of my FIELD WORKERS
THEN the FIELD WORKER should see an alert for a _confirmed match_

We should also explore how confirmed matches could then prompt the user "Do
you want to complete / initiate a _TRACING REQUEST FORM_"?

_____________________
Stuart Campo
Innovation Unit, UNICEF
scampo@unicef.org

+254.718.764526 (Kenya)*
+211.921.379121 (South Sudan)
+256.779.234347 (Uganda)
+1.802.249.8233 (U.S.)
 Skype: stuart.campo

*_currently in Kenya_

www.unicefstories.org

**Comment by baziwane** [comment]
@scampo confirmation of a match will be tracked in a different story from this one. The expectation here is to be able to view the matching child records.
