### ISSUE TITLE
Display number of potential matches on the home screen

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#69]
Pinging @scampo for some additional context on this card. So far there are two options:
a) displaying the number of enquiries that have matches and
b) displaying  the number of child records that have matched enquiries
So far I'm assuming a field admin/worker logged into RapidFTR would see a link on the home/landing page. e.g "4 records matched" ( @scampo pls provide actual text to use). On clicking this link, depending on which of the options above:
Option (a)
they would view a list of enquiries and upon clicking on the enquiry, they can view the list of matching children
Option (b)
they would view the list of child records and upon clicking on the child record, they can view the list of matching enquiries

**Comment by scampo** [comment]
On the first part of the question above, shouldn't A and B effectively be the same? The point with Smart Search / Enquiries is that we are matching two sets of records, so the number of "enquiries that have matches" and the "number of child records that have matched enquiries" should be the same. My thought would be to allow for both, with the 'anchor' being that the match is flagged on whatever record the case worker has generated, e.g. if I registered and ENQUIRY and there is subsequently a match against that enquiry, the system should flag the ENQUIRY with a potential child record match, since I have access to the ENQUIRY but likely not the child record (as I probably did not also register the unaccompanied or separated child).

So perhaps "Matches" is its own button on the home screen with link through to a dedicated MATCHES page that allows for both?

@baziwane , the text will depend on the option, but I think the main distinction is "potential matches (identified by the system)" and, in turn, "validated matches" (validated / confirmed by a human either in the field or at the national / head office level". Can we explore this?

**Comment by baziwane** [comment]
@scampo A and B are logically the same but the determination of the page that will be displayed upon clicking on the link we have to decide which of the options will most be important to users. Basically, my question is "2 potential enquiries matched" would mean we display the 2 enquiries upon clicking on the link and "30 child records potentially matched" would mean we display the 30 child records upon clicking on the link. Let me explore the dedicated matches page as suggested. 
Maybe another question -> is the case worker viewing matches for records (enquiries and child records) they created or all potential matches for records in the instance?

**Comment by rdsubhas** [comment]
I guess the confusion is around:

1 enquiry, 10 matching children, what should we show, what should we link?

a) "1 enquiry has potential matches" - clicking will show the enquiry (aka list of enquiries with matching children)

b) "10 children have potential matches" - clicking will show children (aka list of children with matching enquiries)

**Comment by baziwane** [comment]
GIVEN that I am a FIELD WORKER
WHEN I log into RapidFTR
THEN I should view a link with information on the number of enquiries with potential matches

GIVEN that I am a FIELD WORKER
WHEN I click on the link showing number of enquiries with potential matches
THEN I should view the list of enquiries that have matches

GIVEN that I am a FIELD WORKER
WHEN I select any of the enquries
THEN I should be able to view the details of the enquiry
AND I should be able to view the list of potential matches for this enquiry

**Comment by tomclement** [comment]
All ACs are met, however it looks like not all records that are matched are relevant. We will therefore have to tweak Solr to ensure that only relevant records are returned. This should be played in card #65
