### ISSUE TITLE
Mark/Unmark child as Confirmed Match for an enquiry

### ISSUE THREAD

**Issue by baziwane** [rapidftr/tracker#71]
Marking a child as a confirmed match for an enquiry involves field worker manually highlighting a child record as a match to an enquiry. A field worker would navigate to the potential matches list and select the child from the list and mark as confirmed match.

**Comment by baziwane** [comment]
GIVEN that I am a FIELD WORKER,
WHEN I navigate to the list of potential matches to an enquiry
THEN I should view an icon to "Confirm as Match" on each child record in the list

GIVEN that I am a FIELD WORKER
WHEN I confirm a child record as a match
THEN I should view this record as highlighted at the top of the list

GIVEN that I am a FIELD WORKER
WHEN I confirm a child record as a match to an enquiry
THEN I shouldn't be able to confirm any other child record

GIVEN that I am a FIELD WORKER
WHEN I confirm a child record as a match to an enquiry
THEN I should still be able to view the list of potential matches to the enquiry

**Comment by tomclement** [comment]
In the event that two fieldworkers are separately viewing the potential matches of a particular enquiry, it is possible for each of the fieldworkers to mark a child record as matching. This has the effect that if both fieldworkers mark the same child as a confirmed match, there is no deviation from the expected behaviour. However, if each of the fieldworkers marks a different child as a confirmed match, only the first confirmed child record will show up as a confirmed match. The other confirmed child record will neither show up in the list of confirmed matches nor potential matches. However, unconfirming the first child record will result in the second record showing up as the confirmed match.

A fix for this scenario (by adding validation to ensure that there is ever only one confirmed match) will be added as part of https://github.com/rapidftr/tracker/issues/200

**Comment by tomclement** [comment]
Action items
- [x] Change the text "Matches" to “Potential Matches” to distinguish with confirmed matches
